blog/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
app_name = 'blog'
urlpatterns = [
   	url(r'^$', views.index, name ='index'),
	url('all/', views.all, name ='all'),
	url('history/', views.history, name ='history'),
	url('signin/', views.signin, name ='signin'),
	url('register/', views.register, name ='register'),
	url('signout/', views.signout, name='signout'),
	url('newpost/', views.new_post, name='newpost'),
	url('lk/', views.lk, name='lk'),
	url('post/(?P<post_id>[0-9]+)', views.post, name ='post'),
	]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

urlpatterns = [
    # url(r'^polls/', include('polls.urls')),
    path(r'', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Comments(models.Model):
    title = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.CharField(max_length=20)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.text

blog/views.py
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.template.context_processors import csrf

from .models import Post, Comments
from django.shortcuts import render, redirect
from django.http import Http404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from django.utils import timezone
import time


def index(request):
    latest_post = Post.objects.order_by('-published_date')[:10]
    context = {'latest_post': latest_post}
    return render(request, 'blog/index.html', context)


def all(request):
    latest_post = Post.objects.order_by('-published_date')
    context = {'latest_post': latest_post}
    return render(request, 'blog/all.html', context)


def post(request, post_id):
    if request.POST:
        title = Post.objects.get(id=post_id)
        author = User.objects.get(id=request.user.id)
        text = request.POST['comment']
        comment = Comments(title=title, author=author, text=text)
        comment.save()
    post = Post.objects.get(pk=post_id)
    comments = post.comments_set.all()
    context = {'post': post, 'comments': comments}
    return render(request, 'blog/detail.html', context)


def history(request):

    posts = Post.objects.all()
    datas= {}
    for post in posts:
        date=post.published_date
        date2=date.strftime("%B")
        datas.update({date2:post})
    context = {'posts': posts, 'datas': datas}
    return render(request, 'blog/history.html', context)


def render_to_respose(param, args):
    pass


def signin(request):
    if request.POST:
        user = authenticate(username=request.POST['login'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            context ={'signin_error':'Wrong nickname or password!'}
            return render(request, 'blog/signin.html', context)
    else:
        return render(request, 'blog/signin.html')



def signout(request):
    logout(request)
    return redirect('blog:index')

def register(request):
    if request.POST:
        print (request.POST['login'])
        print (request.POST['email'])
        print (request.POST['password'])
        try:
            user_exists = User.objects.get(username = request.POST['login'])
        except:
            user_exists = False
        if user_exists is False:
            user = User.objects.create_user(username=request.POST['login'], email=request.POST['email'], password=request.POST['password'])
            user.save()
            user = authenticate(username=request.POST['login'], password=request.POST['password'])
            login(request, user)
            return redirect('/')
        else:
            context ={'register_error':'User already exists!'}
            return render(request, 'blog/register.html', context)
    return render(request, 'blog/register.html')



def new_post(request):
    if request.POST:
        author = User.objects.get(id=request.user.id)
        entry = Post(author=author, title = request.POST['title'], text = request.POST['text'], created_date = timezone.now())
        entry.save()
        return redirect('/')
    else:
        return render(request, 'blog/newpost.html')
    return render(request, 'blog/newpost.html')

def lk(request):
    latest_post = Post.objects.filter(author_id=request.user.id)
    comments = Comments.objects.filter(author=request.user)
    context = {'latest_post': latest_post, 'comments': comments}
    return render(request, 'blog/lk.html', context)

blog/templates/about.html
<p>Hello</p>

blog/templates/blog/all.html
{% extends "blog/wrapper.html" %}
{% block content %}
<div class="container">
    {% if latest_post%}
    <div class="panel panel-info">
        <div class="panel-heading">
            <p class="text-center">
                <b>All posts</b>
            </p>
        </div>
    </div>
    {% for post in latest_post%}
    <div class="panel panel-default">
        <div class="panel-heading">
            <a href="/blog/post/{{ post.id }}/">
                <b>
                    {{ post.title }}
                </b>
            </a>
        </div>
        <div class="panel-body">
            {{ post.text }}
            </a>
        </div>
        <p class="text-right">
            <i>
                {{ post.author }},
                {{ post.published_date }}
            </i>
        </p>
    </div>
    {% endfor %}
    {% else %}
    <p class="text-center">
        No blog
    </p>
    {% endif %}
</div>
{% endblock %}

blog/templates/blog/detail.html
{% extends "blog/wrapper.html" %}
{% block content %}
<div class="container">
{% if post%}
<div class="panel panel-default">
    <div class="panel-heading">
        {{ post.title }}
    </div>
    <div class="panel-body">
        {{ post.text }}
    </div>
    <p class="text-right">
        <i>
            {{ post.author }},
            {{ post.published_date }}
        </i>
    </p>
</div>
<p class="text-left">
    Comments:
</p>
    <br/>
    {% for comment in comments %}
    <blockquote>
        {{ comment.text }}
        <footer>
            {{comment.author}}
            {{comment.created_date}}
        </footer>
    </blockquote>
    {% endfor %}
    {% if user.is_authenticated %}
    <form class="text-center" action="{% url 'blog:post' post.id %}" method="post">
        {% csrf_token %}
      <p>
          Your comment:
      </p>
        <p class="text-center">
            <textarea name="comment" cols = 100 rows= 8 required></textarea>
        </p>
        <input type ="submit" value="Enter"/>
    </form>
    {% else%}
    <p>
        Login for comment
    </p>
{% endif %}
{% else %}
<p>
    No post
</p>
{% endif %}
</div>
{% endblock %}

blog/templates/blog/history.html
{% extends "blog/wrapper.html" %}
{% block content %}
<div class="container">
    {% if posts%}
    <div class="panel panel-info">
        <div class="panel-heading">
            <p class="text-center">
                <b>History posts (by month)</b>
            </p>
        </div>
    </div>
    {% for month in datas%}
    <p class="text-center">
        <b>
            {{month}}
        </b>
    </p>
    {% for post in posts%}
    {% if post.published_date|date:"F" in month %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <a href="/blog/post/{{ post.id }}/">
                <b>
                    {{ post.title }}
                </b>
            </a>
        </div>
        <div class="panel-body">
            {{ post.text }}
        </div>
        <p class="text-right">
            <i>
                {{ post.author }},
                {{ post.published_date }}
            </i>
        </p>
    </div>
    {% endif %}
    {% endfor %}
    {% endfor %}
    {% else %}
    <p>
        No blog
    </p>
    {% endif %}
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends "blog/wrapper.html" %}
{% block content %}
<div class="container">
    {% if latest_post %}
    <div class="panel panel-info">
        <div class="panel-heading">
            <p class="text-center">
                <b>Last 10 posts</b>
            </p>
        </div>
    </div>
    {% for post in latest_post %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <a href="{% url 'blog:post' post.id %}">
                <b>
                    {{ post.title }}
                </b>
            </a>
        </div>
        <div class="panel-body">
            {{ post.text }}
        </div>
        <p class="text-right">
            <i>
                {{ post.author }},
                {{ post.published_date }}
            </i>
        </p>
    </div>
    {% endfor %}
    {% else %}
    <p>
        No blog
    </p>
    {% endif %}
</div>
{% endblock %}

blog/templates/blog/lk.html
{% extends "blog/wrapper.html" %}
{% block content %}
<div class="container">
{% if latest_post %}
    <div class="panel panel-info">
        <div class="panel-heading">
            <p class="text-center">
                <b>Your posts</b>
            </p>
        </div>
    </div>
    {% for post in latest_post %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <a href="{% url 'blog:post' post.id %}">
                <b>{{ post.title }}</b>
            </a>
        </div>
        <div class="panel-body">
            {{ post.text }}
        </div>
        <p class="text-right">
            <i>
            {{ post.author }},
            {{ post.published_date }}
            </i>
        </p>
    </div>
    {% endfor %}
    {% else %}
    <div class="panel panel-info">
        <div class="panel-heading">
            <p class="text-center">
                <b>You have no posts</b>
            </p>
        </div>
    </div>
    {% endif %}
    {% if comments %}
        <div class="panel panel-info">
            <div class="panel-heading">
                <p class="text-center">
                    <b>Your comments</b>
                </p>
            </div>
        </div>
    {% for comment in comments %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <a href="{% url 'blog:post' comment.title_id %}">
                <b>{{ comment.text }}</b>
            </a>
        </div>
        <p class="text-right">
            <i>
            {{ comment.created_date }}
            </i>
        </p>
    </div>
    {% endfor %}
    {% else %}
    <div class="panel panel-info">
        <div class="panel-heading">
            <p class="text-center">
                <b>You have no comments</b>
            </p>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

blog/templates/blog/newpost.html
{% extends "blog/wrapper.html" %}
{% block content %}
<div class="container">
    <form class="text-center" action="{% url 'blog:newpost' %}" method="post">
        {% csrf_token %}
        <div class="panel panel-default">
            <div class="panel-body">
                Title:
            </div>
            <textarea name="title" cols = 100 rows= 1 maxlength="200" required></textarea>
            <div class="panel-body">
                Text:
            </div>
            <textarea name="text" cols = 100 rows= 10 maxlength="2000" required></textarea>
            <br/>
            <input type="submit" value="Publish">
        </div>
    </form>
</div>
{% endblock %}

blog/templates/blog/register.html
{% extends "blog/wrapper.html" %}
{% block content %}
<div class="container">
    <form class="text-center" action="{% url 'blog:register' %}" method="post">
        {% csrf_token %}
        <div class="panel panel-default">
            <div class="panel-body">
                Nickname:
            </div>
            <input type="login" name="login" maxlength="20" required>
            <div class="panel-body">
                Password:
            </div>
            <input type="password" name="password" maxlength="20" required>
            <div class="panel-body">
                E-mail:
            </div>
            <input type="email" name="email" maxlength="30" required>
            <br/>
            <br/>
            <input type="submit" value="Register">
            {% if register_error %}
            <br/>
            <br/>
            <div class="alert alert-danger" role="alert">
                {{ register_error }}
            </div>
            {% endif %}
        </div>
</form>
</div>
{% endblock %}

blog/templates/blog/signin.html
{% extends "blog/wrapper.html" %}
{% block content %}
<div class="container">
<form class="text-center" action="{% url 'blog:signin' %}" method="post">
    {% csrf_token %}
    <div class="panel panel-default">
        <div class="panel-body">
            Nickname:
        </div>
        <input type="login" name="login" maxlength="20" required>
        <div class="panel-body">
            Password:
        </div>
        <input type="password" name="password" maxlength="20" required>
        <br/>
        <br/>
        <input type="submit" value="Login">
        {% if signin_error %}
        <br/>
        <br/>
        <div class="alert alert-danger" role="alert">
            {{ signin_error }}
        </div>
        {% endif %}
    </div>
</form>
</div>
{% endblock %}

blog/templates/blog/wrapper.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
    <title>
        AMAKOVEY BLOG
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>

<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'blog:lk' %}">
            {{user}}
        </a>
        {% else %}
        <a class="navbar-brand" href="#">
            ...
        </a>
        {% endif %}
        <div>
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'blog:index' %}">
                        HOMEPAGE
                    </a>
                </li>
                <li>
                    <a href="{% url 'blog:all' %}">
                        ALL POSTS
                    </a>
                </li>
                <li>
                    <a href="{% url 'blog:history' %}">
                        POST HISTORY
                    </a>
                </li>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'blog:signout' %}">
                        LOGOUT
                    </a>
                </li>
                <li>
                    <a href="{% url 'blog:newpost' %}">
                        NEW POST
                    </a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'blog:signin' %}">
                        LOGIN
                    </a>
                </li>
                <li>
                    <a href="{% url 'blog:register' %}">
                        REGISTER
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
</body>
</html>
{% block content %}
{% endblock %}

blog/templates/polls/about.html
<p>Hello</p>

blog/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_messge %}<p><strong>{{ error_message}} </strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>><br />
    {% endfor %}
    <input type="submit" value = "Vote" />
</form>

blog/templates/polls/index.html
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li> <a href = "{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p> No polls </p>>
{% endif %}

blog/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li> {{ choice.choice_text }} -- {{choice.votes}} vote{{ choice.votes|pluralize }} </li>
    {% endfor %}</ul>

<a href = "{% url 'polls:detail' question.id %}"> Vote again? </a>